services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: always
    ports:
      - "3406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-elotus}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-elotus}
      - MYSQL_USER=${MYSQL_USER:-elotus}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-Tantran@2101}
    networks:
      - elotus-network

volumes:
  mysql_data:
    name: elotus-mysql-data

networks:
  elotus-network:
    driver: bridge